version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: arb
      POSTGRES_PASSWORD: arbpass
      POSTGRES_DB: arb
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  app:
    build: .
    environment:
      - PYTHONPATH=/code/src
      - DB_URL=postgresql+psycopg2://arb:arbpass@db:5432/arb
    env_file:
      - .env                  # ваши API-ключи (не коммитим!)
    volumes: ["./src:/code/src"]
    depends_on: [db]
    command: ["sleep", "infinity"]  # во время dev; позже заменим на supervisord

volumes:
  pgdata:
